[project]
name = "acodeai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "langchain-text-splitters>=1.1.2",
    "motor>=3.7.1",
    "openai>=3.13.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pymongo[srv]>=4.18.1",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
acodeai = "acodeai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]
